### ISSUE TITLE
Why the first eigenvector is not constant?

### ISSUE THREAD

**Issue by ceceha** [lawrennd/spectral#1]
When I run demoCircles, I find that the first eigenvector is not constant. Could you tell me the reason ?

**Comment by lawrennd** [comment]
The zero eigenvalue eigenvector is being removed during the inverse operation in SpectralClustering.

Note that this is *not* an efficient way of doing the eigenvalue decomposition, it should be done on the sparse matrix and then there *would* be a zero eigenvector which is constant. Not sure where Guido and Jonny chose to do it this way.

**Comment by ceceha** [comment]
Thank you for your reply!
